version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "hello world"
  execute-github-actions:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: 'Execute GitHub Actions'
          command: |
            curl -X POST \
              -H "Authorization: token ${PAT}" \
              -H "Accept: application/vnd.github.v3+json" \
              ${URL} \
              -d '{ \
                "ref":"main", \
                "inputs": { \
                  "sample": "Hello from CircleCI" \
                } \
              }'

workflows:
  my-workflow:
    jobs:
      - hello-job
      - execute-github-actions